<?php

// app/messages/en.php
$messages = [
    'hello world' => 'Hello World',
    'Ups' => 'Update Settings',
    'Adr' => 'Add Role',
    'Gac' => "Grant Access",
    'Plo' =>'Place Order',
    'Lo' => 'List Orders',
    'adb' => 'Please add bearer',
    'adp'  => 'Add Product',
    'Lp' => 'List all products',
    'adn' => 'Accès refusé',
    'chl' => 'Change Language',
    'hi'      => 'Hello',
    'change'  => 'Change',
    'hlu' => 'Hello User',
    'adu' => 'Add User',
    'Slr' => 'Select Role',
    'usernm' => 'User Name',
    'email' => 'Email',
    'password' => 'Password',
    'rtpass' => 'Re-type new password',
    'ctr' => 'Click to register',
    'gthp' => 'Go to home page',
    'chl' => 'Language',
    'bye' => 'Good Bye %name%',
    'hi-name' => 'Hello %name%',
    'song'    => 'This song is %song%',
];