<div class="container-fluid p-5 m-5">


<div class="table-responsive">
       <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col"><?php echo $this->locale->_('Order Id') ?></th>
                    <th scope="col"><?php echo $this->locale->_('Customer Name') ?></th>
                    <th scope="col"><?php echo $this->locale->_('address') ?></th>
                    <th scope="col"><?php echo $this->locale->_('zip') ?></th>
                    <th scope="col"><?php echo $this->locale->_('Product') ?></th>
                    <th scope="col"><?php echo $this->locale->_('quantity') ?></th>
                 
                  </tr>
                </thead>
                <tbody>
          
           <?php 
            foreach ($data as $k => $v){
              ?>
                  <tr>
                        <td> <?php echo $v->order_id  ?></td>
                        <td> <?php echo $v->customerName  ?></td>
                        <td> <?php echo $v->address  ?></td>
                        <td> <?php echo $v->zip  ?></td>
                        <td> <?php echo $v->product  ?></td>
                        <td> <?php echo $v->quantity  ?></td>
                       
                     </td></tr> <?php          
            }
            ?>  
          </tbody>
       </table>      
      </div>
      </div>